// ─── Single source of truth for plan display (landing + dashboard) ─────────────
// Must stay in sync with backend src/config/plans.js

export const PLANS = {
  free: {
    name: 'Free',
    price: 0,
    label: 'Free forever',
    aiLimit: 999999,
    flashcardLimit: 999999,
    cbtLimit: 3,
    features: [
      '3 practice sessions (10 questions each)',
      'Basic study timer',
      'Limited analytics',
    ],
    notIncluded: [
      'Unlimited CBT practice',
      'Post-UTME practice',
      'Notes & highlights',
      'Streak tracking',
    ],
  },
  daily: {
    name: 'Daily',
    price: 0,
    label: '1-day pass',
    durationDays: 1,
    aiLimit: 999999,
    flashcardLimit: 999999,
    features: [
      'Unlimited AI questions & tutoring',
      'Unlimited CBT tests',
      'All exam types (JAMB, WAEC, Post-UTME)',
      'Full analytics & progress tracking',
      'AI explanations for answers',
    ],
    notIncluded: [],
  },
  weekly: {
    name: 'Weekly',
    price: 1000,
    label: '₦1,000 / week',
    durationDays: 7,
    aiLimit: 999999,
    flashcardLimit: 999999,
    features: [
      'Unlimited CBT tests & study sessions',
      'Unlimited AI questions & tutoring',
      'Unlimited flashcards',
      'All exam types (JAMB, WAEC, Post-UTME)',
      'Smart study timer',
      'Full analytics & progress tracking',
      'Notes & highlights',
      'Streak tracking',
      'AI explanations for answers',
    ],
    notIncluded: [],
  },
  monthly: {
    name: 'Monthly',
    price: 3500,
    label: '₦3,500 / month',
    durationDays: 30,
    aiLimit: 999999,
    flashcardLimit: 999999,
    badge: 'Best Value',
    savings: 'Save ₦500 vs weekly',
    features: [
      'Unlimited CBT tests & study sessions',
      'Unlimited AI questions & tutoring',
      'Unlimited flashcards',
      'All exam types (JAMB, WAEC, Post-UTME)',
      'Smart study timer',
      'Full analytics & progress tracking',
      'Notes & highlights',
      'Streak tracking',
      'AI explanations for answers',
      'Priority support',
    ],
    notIncluded: [],
  },
  yearly: {
    name: 'Yearly',
    price: 29990,
    label: '₦29,990 / year',
    durationDays: 365,
    aiLimit: 999999,
    flashcardLimit: 999999,
    badge: 'Best Savings',
    savings: 'Save 30% vs monthly',
    features: [
      'Unlimited CBT tests & study sessions',
      'Unlimited AI questions & tutoring',
      'Unlimited flashcards',
      'All exam types (JAMB, WAEC, Post-UTME)',
      'Smart study timer',
      'Full analytics & progress tracking',
      'Notes & highlights',
      'Streak tracking',
      'AI explanations for answers',
      'Priority support',
    ],
    notIncluded: [],
  },
  addon: {
    name: 'AI Add-on',
    price: 500,
    label: '₦500 one-time',
    aiLimit: 60,
    durationDays: 5,
    features: [
      '60 extra AI-generated questions',
      'Added to your current plan',
      'Expires in 5 days',
    ],
  },
} as const;

export type PlanKey = keyof typeof PLANS;
